name: Build and deploy prod
on:
  push:
    branches:
      - 'main'

jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy Sanity
    steps:
      - uses: actions/checkout@v3
      - uses: sanity-io/github-action-sanity@v0.5-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
        with:
          args: . deploy
